In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
# Model
from sklearn.neural_network import MLPClassifier
# Data process
from sklearn.model_selection import KFold, train_test_split
# Metrics
from sklearn.metrics import log_loss, accuracy_score, confusion_matrix

In [4]:
# データ読み込み
df = pd.read_csv('../data/day2_onehot.csv')
df.head()

,state,category_Academic,category_Accessories,category_Action,category_Animation,category_Anthologies,category_Apparel,category_Apps,category_Architecture,category_Art,...,currency_GBP,currency_USD,currency_others,country_AU,country_CA,country_GB,country_US,country_others,days,goal
0,False,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,58.0,1000.0
1,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,59.0,30000.0
2,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,44.0,45000.0
3,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,29.0,5000.0
4,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,55.0,19500.0

In [5]:
# 標準化
from sklearn.preprocessing import StandardScaler

In [10]:
stdsc = StandardScaler()
x_df_std = df.drop(['days', 'goal'], axis=1)
x_df_std['std_days'] = stdsc.fit_transform(df['days'].values.reshape(-1,1))
x_df_std['std_goal'] = stdsc.fit_transform(df['goal'].values.reshape(-1,1))
x_df_std.head()

,state,category_Academic,category_Accessories,category_Action,category_Animation,category_Anthologies,category_Apparel,category_Apps,category_Architecture,category_Art,...,currency_GBP,currency_USD,currency_others,country_AU,country_CA,country_GB,country_US,country_others,std_days,std_goal
0,False,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0.372011,-0.040630
1,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0.387183,-0.016124
2,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0.159597,-0.003448
3,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,-0.067989,-0.037250
4,False,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0.326493,-0.024997

In [ ]:
X = x_df_std.iloc[:,1:].values
y = df["state"].values * 1

test_size = 0.2        # 全データのうち、何%をテストデータにするか（今回は20%に設定）
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=1234) # ホールドアウト法を実行（テストデータはランダム選択）
display(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

clf = MLPClassifier(hidden_layer_sizes=(100,100,), activation='relu', solver='adam', batch_size=50)
clf = clf.fit(X_train, y_train)
print("score=", clf.score(X_test, y_test))
print(clf.predict(X_test)) #予測したい場合

(302928, 119)

(75733, 119)

(302928,)

(75733,)